//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEZpbGVEYXRhU2V0IHhtbG5zPSJodHRwOi8vdGVtcHVyaS5vcmcvRmlsZURhdGFTZXQueHNkIj4NCiAgPFNlcnZlcnM+DQogICAgPFNlcnZlck51bWJlcj4xMDAyPC9TZXJ2ZXJOdW1iZXI+DQogICAgPEZpcnN0TmFtZT5SYWxwaGllPC9GaXJzdE5hbWU+DQogICAgPExhc3ROYW1lPkphbWVzPC9MYXN0TmFtZT4NCiAgICA8U3VwcHJlc3NDaGl0PmZhbHNlPC9TdXBwcmVzc0NoaXQ+DQogIDwvU2VydmVycz4NCiAgPFNlcnZlcnM+DQogICAgPFNlcnZlck51bWJlcj4xMDA1PC9TZXJ2ZXJOdW1iZXI+DQogICAgPEZpcnN0TmFtZT5DaGFybGllPC9GaXJzdE5hbWU+DQogICAgPExhc3ROYW1lPkhhY2tlcjwvTGFzdE5hbWU+DQogICAgPFN1cHByZXNzQ2hpdD5mYWxzZTwvU3VwcHJl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LegacyFile {
            get {
                return ResourceManager.GetString("LegacyFile", resourceCulture);
            }
        }
    }
}
